###
# signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "Tom Smith",
  "email": "tom@example.com",
  "password": "qwertz1234"
}

###
# signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "tom@example.com",
  "password": "qwertz1234"
}

###
# me
GET http://localhost:3000/auth/me

###
# refresh
POST http://localhost:3000/auth/refresh

###
# logout
POST http://localhost:3000/auth/logout