export const ticketsResposeCodes = {
  TICKETS_FETCHED: 200,
  TICKET_FETCHED: 200,
  TICKET_CREATED: 201,
  TICKET_UPDATED: 200,
  TICKET_DELETED: 200,

  STATUS_INVALID: 400,
  PRIORITY_INVALID: 400,
  TICKET_ID_REQUIRED: 400,
  TICKET_ID_INVALID: 400,
  CREATOR_ID_REQUIRED: 400,
  CREATOR_ID_INVALID: 400,
  AGENT_ID_INVALID: 400,
  SUBJECT_REQUIRED: 400,
  SUBJECT_TOO_LONG: 400,
  DESCRIPTION_REQUIRED: 400,
  UPDATED_AT_INVALID: 400,
  CREATED_AT_REQUIRED: 400,
} as const

export type TicketsResponseCode = keyof typeof ticketsResposeCodes
export const ticketsResponseCode = <T extends TicketsResponseCode>(e: T) => e
